### ISSUE TITLE
Move C++ manifest reader library from Office development tree

### ISSUE THREAD

**Issue by ghost** [microsoft/continuity#2]
Move the C++ manifest reader library from Office's internal source tree to this public repo. Put the code in a manifest library project, not in the root. Don't include Office build files, just the headers and the code. Do not include the host-integration library, as that is Office-specific and irrelevant to OSS consumers.

Ensure the public API / ABI is stable. Simple types or IUnknown. Explicit calling convention.

Institute a version file for this library. It should be bumped as part of the PR, and the PR validation should fail if the bump isn't included.

Create automation to build a DLL and publish with headers into a NuGet package using the version number from the version file. Prefer to use an ADO CI loop for this. Alternatively, start with a script that is run manually after every merged PR.

Back in the Office source tree, delete the reactnative_platformsdk project and instead pull in DLL/headers via NuGet. Incorporate it into the build, and verify that internal test apps and in-app hooks continue to work as expected.

**Comment by afoxman** [comment]
Release pipeline is done. NuGet publishing is done. Office integration is in progress. Additional code-changes are needed.

**Comment by afoxman** [comment]
Office consumption is done. Loop is complete.
